### ISSUE TITLE
Errors while cloning

### ISSUE THREAD

**Issue by RobinGeelen** [sergirovira/fastparameterselection#6]
I'm getting the following errors while cloning:

Cloning into 'fastparameterselection'...
remote: Enumerating objects: 277, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 277 (delta 13), reused 14 (delta 5), pack-reused 244 (from 1)
Receiving objects: 100% (277/277), 637.82 KiB | 4.25 MiB/s, done.
Resolving deltas: 100% (150/150), done.
error: invalid path 'src/aux.py'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by sergirovira** [comment]
Hello Robin, we have fixed the issue. Turns out you can't have a file named aux in the repo and clone it to Windows. The rest should work just fine, let us know if that is not the case please.

**Comment by RobinGeelen** [comment]
I'm still getting some errors that the lattice estimator cannot be imported (I did clone the relevant submodule, so not sure what is the cause).



Warning: Failed to import lattice_estimator, some options will not work
Warning: Failed to import lattice_estimator, some options will not work
Warning: Failed to import lattice_estimator, some options will not work
Secret dist.   : The distribution of the secret (can be either binary or ternary)
LWE dim.       : The Learning With Errors (LWE) dimension
log q          : The size of the modulus q in bits
usvp (Eq. 14)  : The output of Eq. 14 of https://eprint.iacr.org/2024/1001
usvp_s (Eq. 16): The output of Eq. 16 of https://eprint.iacr.org/2024/1001
bdd (Eq. 17)   : The output of Eq. 17 of https://eprint.iacr.org/2024/1001
bdd_s (Eq. 20) : The output of Eq. 20 of https://eprint.iacr.org/2024/1001
................................................................


name 'LWE' is not defined
name 'LWE' is not defined
name 'LWE' is not defined
name 'LWE' is not defined
name 'LWE' is not defined
name 'LWE' is not defined
name 'LWE' is not defined
name 'LWE' is not defined
name 'LWE' is not defined
name 'LWE' is not defined
name 'LWE' is not defined
name 'LWE' is not defined
name 'LWE' is not defined
name 'LWE' is not defined
name 'LWE' is not defined
name 'LWE' is not defined
name 'LWE' is not defined
name 'LWE' is not defined
name 'LWE' is not defined
name 'LWE' is not defined
name 'LWE' is not defined
name 'LWE' is not defined
name 'LWE' is not defined
name 'LWE' is not defined
name 'LWE' is not defined
name 'LWE' is not defined
name 'LWE' is not defined
name 'LWE' is not defined
name 'LWE' is not defined
name 'LWE' is not defined
name 'LWE' is not defined
name 'LWE' is not defined
name 'LWE' is not defined
Secret dist. | LWE dim. | log q | usvp (Eq. 14) | usvp_s (Eq. 16) | bdd (Eq. 17) | bdd_s (Eq. 20)
-------------+----------+-------+---------------+-----------------+--------------+---------------
binary       | 1024     | 20    | 170           | 172             | 0            | 173
binary       | 1024     | 21    | 161           | 163             | 0            | 164
binary       | 1024     | 22    | 153           | 155             | 0            | 156
binary       | 1024     | 23    | 146           | 148             | 0            | 149
binary       | 1024     | 24    | 139           | 142             | 0            | 142
binary       | 1024     | 25    | 133           | 136             | 0            | 136
binary       | 1024     | 26    | 128           | 130             | 0            | 130
binary       | 1024     | 27    | 123           | 125             | 0            | 125
binary       | 1024     | 28    | 118           | 120             | 0            | 120
binary       | 1024     | 29    | 114           | 116             | 0            | 116
binary       | 1024     | 30    | 110           | 112             | 0            | 112
binary       | 1024     | 35    | 93            | 96              | 0            | 95
binary       | 1024     | 40    | 82            | 84              | 0            | 83
binary       | 1024     | 41    | 80            | 82              | 0            | 81
binary       | 1024     | 42    | 78            | 80              | 0            | 79
binary       | 1024     | 43    | 76            | 78              | 0            | 77
binary       | 1024     | 44    | 75            | 76              | 0            | 76
binary       | 1024     | 45    | 73            | 75              | 0            | 74
binary       | 1024     | 46    | 72            | 73              | 0            | 72
binary       | 1024     | 47    | 70            | 72              | 0            | 71
binary       | 1024     | 48    | 69            | 70              | 0            | 69
binary       | 1024     | 49    | 68            | 69              | 0            | 68
binary       | 1024     | 50    | 67            | 68              | 0            | 67
binary       | 1024     | 51    | 65            | 66              | 0            | 65
binary       | 1024     | 52    | 64            | 65              | 0            | 64
binary       | 1024     | 53    | 63            | 64              | 0            | 63
binary       | 1024     | 54    | 62            | 63              | 0            | 62
binary       | 1024     | 55    | 61            | 62              | 0            | 61
binary       | 1024     | 56    | 61            | 61              | 0            | 60
binary       | 1024     | 57    | 60            | 60              | 0            | 59
binary       | 1024     | 58    | 59            | 59              | 0            | 58
binary       | 1024     | 59    | 58            | 58              | 0            | 57
binary       | 1024     | 60    | 57            | 57              | 0            | 56


Warning: Bdd set to 0

**Comment by sergirovira** [comment]
There was a missing pull request, you should get the correct values for bdd now. However

**Comment by RobinGeelen** [comment]
I'm getting
`error: invalid path '__pycache__/aux.cpython-310.pyc'
Updating d09c4d9..5a34326`
when doing git pull. The values for bdd are still 0.
